apiVersion: v1
kind: Deployment
metadata:
  name: gray-deploy-test-v1

spec:
  replicas: 1
  selector:
     matchLabels:
      app: gray-deploy-test-v1
  template:
    metadata:
      labels:
        app: gray-deploy-test-v1
    spec:
      containers:
        - name: gray-deploy-test-v1
          image: grayDeploy/test-v1:latest
          ports:
            - containerPort: 8001

---
kind: Service
apiVersion: v1
metadata:
  name: gray-deploy-test-v1
spec:
  selector:
    app: gray-deploy-test-v1
  ports:
    - port: 8001
